platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/qiime2/simple-remote-directory-resource
    version: latest
params:
  PATH: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
inputs:
  - name: covid-ci
  - name: input1
  - name: input2
  - name: input3
  - name: input4
outputs:
  - name: outputs
run:
  path: covid-ci/bin/execute.py
