platform: linux
image_resource:
  type: docker-image
  source:
    repository: qiime2/simple-remote-directory-resource
    version: latest
params:
  PATH: /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
inputs:
  - name: covid-ci
  - name: input
outputs:
  - name: output
run:
  path: covid-ci/bin/transfer.py
