resource_types:
  - name: simple-remote-directory-resource
    type: docker-image
    source:
      repository: qiime2/simple-remote-directory-resource

resources:
  - name: covid-ci
    type: git
    source:
      uri: https://github.com/caporaso-lab/covid-ci
      branch: master

  - name: upload-gisaid
    type: simple-remote-directory-resource
    check_every: 1m
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_upload_gisaid))
  
  - name: upload-metadata-gisaid
    type: simple-remote-directory-resource
    check_every: 1m
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_upload_metadata_gisaid))

  - name: cleaned-metadata-gisaid
    type: simple-remote-directory-resource
    check_every: 1m
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_cleaned_metadata_gisaid))

  - name: upload-az-tgen
    type: simple-remote-directory-resource
    check_every: 1m
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_upload_az_tgen))

  - name: upload-az-other
    type: simple-remote-directory-resource
    check_every: 1m
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_upload_az_other))

  - name: seqs-gisaid
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_seqs_gisaid))

  - name: seqs-az-tgen
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_seqs_az_tgen))

  - name: seqs-az-other
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_seqs_az_other))

  - name: seqs-az-focal
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_seqs_az_focal))

  - name: filtered-seqs-gisaid
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_filtered_seqs_gisaid))

  - name: view-seqs-gisaid
    type: simple-remote-directory-resource
    check_every: 48h
    source:
      hostname: ((hostname))
      username: ((username))
      private_key: ((private_key))
      key_type: ((key_type))
      path: ((path_view_seqs_gisaid))

jobs:
  - name: import-gisaid
    public: true
    plan:
      - get: covid-ci
      - get: upload-gisaid
        trigger: true
      - task: import-gisaid
        file: covid-ci/tasks/execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: import
          Q2_INPUT: input1
          Q2_FORMAT: GISAIDDNAFASTAFormat
          Q2_TYPE: FeatureData[Sequence]
          Q2_OUTPUT: ((path_seqs_gisaid))

          SLURM_cpus_per_task: 1
          SLURM_time: 0:20:00
          SLURM_mem: 16384

        input_mapping:
          input1: upload-gisaid

      - put: seqs-gisaid
        params:
          source: outputs/result/

  - name: clean-metadata
    public: true
    plan:
      - get: covid-ci
      - get: upload-metadata-gisaid
        trigger: true
      - task: clean-metadata
        file: execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))
          
          SCRIPT: rename_md_col.py
          SCRIPT_I_input: input1
          SCRIPT_output: ((path_cleaned_metadata_gisaid))

          SLURM_cpus_per_task: 1
          SLURM_time: 0:05:00
          SLURM_mem: 4096

        input_mapping:
          input1: upload-metadata-gisaid
      
      - put: cleaned-metadata-gisaid
        params:
          source: outputs/result/


  - name: filter-gisaid
    public: true
    plan:
      - get: covid-ci
      - get: seqs-gisaid
        passed: [import-gisaid]
        trigger: true
      - get: cleaned-metadata-gisaid
        passed: [clean-metadata]
        trigger: true
      - task: match-gisaid-metadata
        file: covid-ci/tasks/execute2.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: feature_table::filter_seqs
          Q2_I_data: input1
          Q2_M_metadata: input2
          Q2_O_filtered_data: .

          SLURM_cpus_per_task: 1
          SLURM_time: 0:30:00
          SLURM_mem: 4096

        input_mapping:
          input1: seqs-gisaid
          input2: cleaned-metadata-gisaid

      - task: filter-gisaid
        file: covid-ci/tasks/execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: genome_sampler::filter_seqs
          Q2_I_sequences: input1
          Q2_P_min_length: 20000
          Q2_O_filtered_sequences: ((path_filtered_seqs_gisaid))

          SLURM_cpus_per_task: 1
          SLURM_time: 0:30:00
          SLURM_mem: 4096

        input_mapping:
          input1: outputs/filtered_data
      - put: filtered-seqs-gisaid
        params:
          source: outputs/filtered_sequences/

  - name: view-gisaid
    public: true
    plan:
      - get: covid-ci
      - get: filtered-seqs-gisaid
        passed: [filter-gisaid]
        trigger: true
      - task: view-gisaid
        file: covid-ci/tasks/execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: feature_table::tabulate_seqs
          Q2_I_data: input1
          Q2_O_visualization: ((path_view_seqs_gisaid))

          SLURM_cpus_per_task: 1
          SLURM_time: 1:00:00
          SLURM_mem: 16384
          
        input_mapping:
          input1: filtered-seqs-gisaid
      - put: view-seqs-gisaid
        params:
          source: outputs/visualization/

  - name: import-az-tgen
    public: true
    plan:
      - get: covid-ci
      - get: upload-az-tgen
        trigger: true
      - task: import-az-tgen
        file: covid-ci/tasks/execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: import
          Q2_INPUT: input1
          Q2_FORMAT: GISAIDDNAFASTAFormat
          Q2_TYPE: FeatureData[Sequence]
          Q2_OUTPUT: ((path_seqs_az_tgen))

          SLURM_cpus_per_task: 1
          SLURM_time: 0:20:00
          SLURM_mem: 4096

        input_mapping:
          input1: upload-az-tgen
      - put: seqs-az-tgen
        params:
          source: outputs/result/

  - name: import-az-other
    public: true
    plan:
      - get: covid-ci
      - get: upload-az-other
        trigger: true
      - task: import-az-other
        file: covid-ci/tasks/execute1.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: import
          Q2_INPUT: input1
          Q2_FORMAT: GISAIDDNAFASTAFormat
          Q2_TYPE: FeatureData[Sequence]
          Q2_OUTPUT: ((path_seqs_az_other))

          SLURM_cpus_per_task: 1
          SLURM_time: 0:20:00
          SLURM_mem: 4096

        input_mapping:
          input1: upload-az-other
      - put: seqs-az-other
        params:
          source: outputs/result/

  - name: merge-focal-seqs
    public: true
    plan:
      - get: covid-ci
      - get: seqs-az-tgen
        passed: [import-az-tgen]
        trigger: true
      - get: seqs-az-other
        passed: [import-az-other]
        trigger: true
      - task: merge-focal-seqs
        file: covid-ci/tasks/execute2.yaml
        params:
          HOSTNAME: ((hostname))
          USERNAME: ((username))
          PRIVATE_KEY: ((private_key))
          KEY_TYPE: ((key_type))
          WORKDIR: ((workdir))

          Q2_ACTION: feature_table::merge_seqs
          Q2_I_data: input1 input2
          Q2_O_merged_data: ((path_seqs_az_focal))

        input_mapping:
          input1: seqs-az-tgen
          input2: seqs-az-other
      - put: seqs-az-focal
        params:
          source: outputs/merged_data/

    # - name: sample-longitudinal

    # - name: sample-diversity

    # - name: sample-neighbors

    # - name: summarize-selections

    # - name: combine-selections

    # - name: filter-to-subsample

    # - name: merge-seqs

    # - name: export
